### PR TITLE
🪲 Bug-Fix

### PR DESCRIPTION
**Pull request by felix-d1strict**
Fixed an bug that caused a fatal error if no questionID was specified.

### CODE REVIEW

**Comment by TitusKirch** [comment]
@felix-d1strict Thank you for this first pull request from you. If you would like to help further develop the project in the future, here are 4 small things:

1. please do not use emojis in the commit messages.
2. use clearer commits messages (this helps to keep track of what you have done in larger pull requests)
3. always create an issue beforehand so that everyone knows what is being worked on.
4. always use a PR for one thing only and don't mix bugfixes, features etc. in one PR.


Greetings and many thanks
Titus

**Comment by TitusKirch** [comment]
And I asked @Hanashi to be the reviser because he edited the file at the end.

**Comment by felix-d1strict** [comment]
@TitusKirch Sorry, point 4 was not intended that way. The Git client committed directly to this PR, although I didn't want that originally.
Should I revert the last commit?

**Comment by TitusKirch** [comment]
> Should I revert the last commit?

@dependabot rebase

**Review by Hanashi — APPROVED** [review]

**Pull request merged**
